name: Deploy Next.js to Hetzner

on:
  push:
    branches:
      - develop
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ARTIFACT_SSH_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./frontend/ ${{ secrets.ARTIFACT_USERNAME }}@${{secrets.ARTIFACT_HOST}}:/root/art-webshop/frontend

      - name: Install dependencies and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.ARTIFACT_USERNAME }}@${{secrets.ARTIFACT_HOST}} << 'EOF'
            cd /root/art-webshop/frontend
            npm install
            npm run build
            pm2 restart nextjs || pm2 start npm --name "nextjs" -- start
          EOF
